# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Smrithi Anuj Kumar
title: Experienced Data Analyst
email: smrithianuj3113@gmail.com
website: www.linkedin.com/in/smrithi-ekkadu

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: smrithi-ekkadu
linkedin_username: smrithi-ekkadu
twitter_username: smrithianuj

# Additional icon links
additional_links:
  - title: Portfolio
    icon: fas fa-globe
    url: https://github.com/smrithianuj/portfolio

# Google Analytics and Tag Manager
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Smrithi Anuj Kumar, an experienced Data Analyst with over 5 years of expertise in scalable software development, data engineering, and process optimization. I specialize in Python, SQL, and cloud technologies to deliver impactful, data-driven solutions.

content:
  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Google Data Analytics
        caption: Completed
        description: |
          Gained expertise in cleaning, organizing, and analyzing data using Python, SQL, and visualization tools. Mastered the application of data-driven decision-making and storytelling with data.

      - layout: left
        title: AWS Cloud Practitioner (CLF-C02)
        caption: Completed
        description: |
          Demonstrated foundational knowledge of AWS services and cloud computing. Acquired skills in designing scalable, cost-efficient solutions and understanding security and compliance practices.

      - layout: left
        title: Microsoft Azure AI Fundamentals
        caption: Ongoing
        description: |
          Learning the basics of artificial intelligence and machine learning on Microsoft Azure. Building skills in implementing AI solutions using Azure Machine Learning Studio.

      - layout: left
        title: AI Agents in LangGraph
        caption: Ongoing
        description: |
          Engaged in advanced studies of generative AI and autonomous agents. Developing expertise in using LangChain to build robust AI workflows for real-world applications.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Graduate Teaching Assistant
        sub_title: University of Texas at Arlington
        caption: Jan 2023 - Present
        description: |
          Assisted in courses on predictive modeling and data analytics. Facilitated student understanding through lectures, tutorials, and office hours.

      - layout: left
        title: Senior Data Analyst
        sub_title: Reliance Industries LTD
        caption: Nov 2020 - Dec 2022
        description: |
          - Developed scalable reporting systems with Tableau.
          - Automated SQL/Python ETL processes, improving operational efficiency by 40%.
          - Aligned technical solutions with business goals.

      - layout: left
        title: Business Analyst
        sub_title: Saboo Motors
        caption: Mar 2017 - Oct 2020
        description: |
          - Streamlined cloud-based data processes, improving reporting accuracy by 30%.
          - Created Power BI dashboards for resource management.
          - Enhanced Agile workflows for requirement prioritization.

      - layout: left
        title: Associate Operations Analyst
        sub_title: Franklin Templeton Investments
        caption: May 2016 - Feb 2017
        description: |
          - Streamlined transaction workflows with SQL, boosting processing speed by 30%.
          - Improved operational efficiency with robust data governance.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Texas at Arlington
        sub_title: Master of Science, Information Systems
        caption: Jan 2023 - Present
        description: | 
          GPA: 3.9

      - layout: left
        title: Osmania University
        sub_title: Bachelor of Commerce and Computer Science
        caption: Jul 2013 - May 2016
        description: |
          GPA: 4.0

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: KPI Dashboards
        description: | #
          <p style="text-align:center;">Designed Power BI dashboards for real-time analytics, enabling faster decision-making.</p>

      - layout: top-middle
        title: AWS Cloud Migration
        description: | #
          <p style="text-align:center;">Migrated data infrastructure to AWS, improving scalability and reducing processing times by 20%.</p>

      - layout: top-middle
        title: Trading Insights with Machine Learning
        description: | #
          <p style="text-align:center;">Developed predictive models to analyze market patterns, enhancing decision efficiency.</p>

  - title: Skills
    layout: text
    content: |
      - Technologies: Python, Java, SQL, MongoDB, Elasticsearch
      - Data Engineering: ETL Pipelines, Star/Snowflake Schemas
      - Visualization Tools: Power BI, Tableau, Excel
      - Cloud Platforms: AWS, Snowflake
      - Agile: Scrum, Kanban, Sprint Planning
      - Tools: Git, JIRA, Figma, Visio

# Footer
footer_show_references: true
references_title: References Available Upon Request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
